# -*- coding: utf-8 -*-
"""PRODIGY_DS_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dE7OqHA5wq3SDpdUbCq1UxFp8Q_xN9T
"""

# Task 2 - Titanic EDA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

# Basic EDA
print("Dataset Shape:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())

#  Survival by Gender
plt.figure(figsize=(10, 6))
sns.countplot(x='sex', hue='survived', data=df, palette='pastel')
plt.title('Survival by Gender - Titanic Dataset')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.legend(['Not Survived', 'Survived'])
plt.show()

#  Survival by Passenger Class
plt.figure(figsize=(10, 6))
sns.countplot(x='pclass', hue='survived', data=df, palette='Set2')
plt.title('Survival by Passenger Class - Titanic Dataset')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.legend(['Not Survived', 'Survived'])
plt.show()

#  Age Distribution
plt.figure(figsize=(10, 6))
plt.hist(df['age'].dropna(), bins=30, color='skyblue', edgecolor='black', alpha=0.7)
plt.title('Age Distribution - Titanic Passengers')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

#  Fare Distribution
plt.figure(figsize=(10, 6))
plt.hist(df['fare'], bins=30, color='lightgreen', edgecolor='black', alpha=0.7)
plt.title('Fare Distribution - Titanic Passengers')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.show()





