# -*- coding: utf-8 -*-
"""PRODIGY_DS_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dE7OqHA5wq3SDpdUbCq1UxFp8Q_xN9T
"""

# Task 2 - Titanic EDA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')

# Basic EDA
print("Dataset Shape:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())

# Visualizations
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. Survival by Gender
sns.countplot(x='sex', hue='survived', data=df, ax=axes[0,0], palette='pastel')
axes[0,0].set_title('Survival by Gender', fontsize=14, fontweight='bold')

# 2. Survival by Passenger Class
sns.countplot(x='pclass', hue='survived', data=df, ax=axes[0,1], palette='Set2')
axes[0,1].set_title('Survival by Passenger Class', fontsize=14, fontweight='bold')

# 3. Age Distribution by Survival
sns.histplot(data=df, x='age', hue='survived', bins=30, ax=axes[1,0], kde=True, palette='coolwarm')
axes[1,0].set_title('Age Distribution by Survival', fontsize=14, fontweight='bold')

# 4. Fare vs Survival
sns.boxplot(x='survived', y='fare', data=df, ax=axes[1,1], palette='viridis')
axes[1,1].set_title('Fare Distribution by Survival', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10, 6))
numeric_cols = df.select_dtypes(include=['number'])
sns.heatmap(numeric_cols.corr(), annot=True, cmap='coolwarm', center=0)
plt.title('Feature Correlation Heatmap', fontsize=14, fontweight='bold')
plt.show()

